name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu_latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeouts 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Ruby and Install Gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install Webpacker
        run: bundle exec rails webpacker:install

      - name: Install Yarn
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build and Run Tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          RAILS_ENV: test
          POSTGRES_USER: postgres
        run: |
          sudo apt-get -yqq install libpq-dev
          bundle exec rails db:prepare
          bundle exec rspec spec
